require('galbie.plugins')

-- require('galbie.autopairs')
-- require('galbie.autotag')
require('galbie.cmp')
-- require('galbie.lsp')
-- require('galbie.lsp_saga')
require('galbie.lsp_map')
require('galbie.lspconfig')
-- require('galbie.mason')
require('galbie.null_ls')
-- require('galbie.nvim_tree')
require('galbie.telescope')
require('galbie.treesitter')
