#!/bin/sh

WORKSPACE_PATH=""

createWindow() {
    session=$1
    window=$2
    shift
    shift
    hasWindow=$(tmux list-windows -t $session | grep "$window")
    if [ -z "$hasWindow" ]; then
        cmd="tmux neww -t $session: -n $window -d"
        if [ $# -gt 0  ]; then
            cmd="$cmd $@"
        fi

        echo "Creating window(\"$hasWindow\"); $cmd"
        eval $cmd
    fi
}

createSession() {
    session=$1
    window=$2
    shift
    shift
    cmd="tmux new -s $session -d -n $window $@> /dev/null 2>&1"

    echo "Creating session: $cmd"
    eval $cmd

    tmux select-window -t $session $window:0
    tmux split-window -v
}

echo "${1}"

while [ "$#" -gt 0  ]; do
    curr=$1
    shift

    case "$curr" in 
    "-t")
        createSession temp primary
        tmux -2 attach-session -t temp
        ;;

    *) echo "Unavailable commands.... $curr"
    esac
done
